### ISSUE TITLE
Can a GeoTIFF file from a GeoServer be applied to this Plugin?

### ISSUE THREAD

**Issue by blairscriven** [danwild/leaflet-geotiff-2#13]
For my project, this plugin seems to have the min-max value renderer that I need; however, my GeoTIFF data is currently in a GeoServer, and I am not sure if I can bring the file in as a simple URL. Has anyone succesfully done this?

**Comment by danwild** [comment]
If you already have a geoserver, I would re-evaluate the need to use this plugin (i.e. why not just publish your geotiff as a WMS and consume via leaflet that way?).

This plugin is not designed to consume a tile service directly, however depending on how your server is configured this might be achievable by fetching the data in javascript using a `GetMap` request (for target bounds), then pass the image to the `leaflet-geotiff-2` plugin (or possibly passing the GetMap url as an arg to `leaflet-geotiff-2` ...I haven't tested this.
