### ISSUE TITLE
L.leafletGeotiff does not exists on type

### ISSUE THREAD

**Issue by martinhschei** [danwild/leaflet-geotiff-2#14]
I'm getting an error on this line: "L.leafletGeotiff(URL, options).addTo(this.map);".

The error says "L.leafletGeotiff does not exists on type...."

This has probably something to do with the import - i'm doing it like this:

import GeoTIFF, { fromUrl, fromUrls, fromArrayBuffer, fromBlob } from 'geotiff';
import * as L from 'leaflet';
import 'leaflet-geotiff-2';

Suggestions?

**Comment by danwild** [comment]
Hi @martinhschei 

Seems like a typescript issue (this lib has no typings)?

What else is in the trace?

This issue tracker is for reporting specific issues with the plugin tho, for general javascript/project configuration questions you'll probably be better of asking on stackoverflow

**Comment by martinhschei** [comment]
Solved - not a bug with this package.
