### ISSUE TITLE
How to Install this PlugIn

### ISSUE THREAD

**Issue by blairscriven** [danwild/leaflet-geotiff-2#16]
I have been having issues with adding this plugin to my leaflet application, and it would be helpful to hear how others got this to work for them.

I am using a hosted version of Leaflet through the unpkg CDN. I am also using a CDN for the GeoTiff.js library, and I have the newest versions of the plotty.js and leaflet-geotiff.js src scripts directly in the same folder as my HTML file. It looks like this:

<script src="https://cdn.jsdelivr.net/npm/geotiff"></script>
<script src="plotty.js"></script>
<script src="leaflet-geotiff-2.js"></script>

Running the code: _import "leaflet-geotiff-2";_
doesn't work due to imports being used outside of modules. I also get some CORS issues and  the "L.leafletGeotiff was not found" error. But I'll be honest, I know I am probably just setting this plugin incorrectly. I know npm and node.js is a common way of getting this to work, but I haven't touched those yet due to not having worked with them before. If npm and node.js is the only way to get this plugin to work, I'd like to know.

**Comment by danwild** [comment]
Have you looked at the example? It uses CDN.

https://danwild.github.io/leaflet-geotiff-2/

**Comment by blairscriven** [comment]
I used the code in the example as a guide and I got the plugin to work! Thanks for that!

Unfortunately, I got the same issue as #15, which I think is because I am connecting to a GeoServer (you mentioned that GeoServer is a tile service, which this plugin is not designed to work with).

**Comment by xlcrr** [comment]
@danwild the link to the CDN 404s, could you paste the solution here please?

Edit 1: found a link to geotiff package

```
https://www.npmjs.com/package/geotiff/v/1.0.0-beta.13
```
