### ISSUE TITLE
no geotiff display

### ISSUE THREAD

**Issue by pedro-vicente** [danwild/leaflet-geotiff-2#24]
opening /demo/index.html
as local (opening Firefox) 

does not display the TIFF image

same as opening inside  a web server (apache)

**Comment by danwild** [comment]
What do you see in the browser console?

**Comment by pedro-vicente** [comment]
using the default

const windSpeedUrl = "http://127.0.0.1:5500/demo/wind_speed.tif";

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:5500/demo/wind_speed.tif. (Reason: CORS request did not succeed).

so, I modified to the URL

const windSpeedUrl = "https://danwild.github.io/leaflet-geotiff-2/wind_speed.tif";

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://danwild.github.io/leaflet-geotiff-2/wind_speed.tif. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

this may have a fix,

**Comment by pedro-vicente** [comment]
with edge

> geotiff.bundle.js:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
> jquery-3.3.1.min.js:2 Uncaught Error: GeoTIFF not defined
>     at initialize (leaflet-geotiff.js:71)
>     at new i (leaflet.js:5)
>     at Object.L.leafletGeotiff (leaflet-geotiff.js:516)
>     at HTMLDocument.<anonymous> (demo.js:17)
>     at l (jquery-3.3.1.min.js:2)

**Comment by danwild** [comment]
This issue tracker for specific issues with the plug-in only.

The problems you are describing are related to your use of the plugin - these "how to" questions are better suited to a google search or discussion on forums such as stackoverflow.

**Comment by danwild** [comment]
See: https://danwild.github.io/leaflet-geotiff-2/
