### ISSUE TITLE
Image render pipeline

### ISSUE THREAD

**Issue by Mforcen** [danwild/leaflet-geotiff-2#30]
Hello to all,
I was thinking about the render pipeline of this addon.

In this case, the layer creates a mainly transparent image in which the rendered image is projected in cpu time.
This shouldn't be a problem in the majority of cases, but it does not scale well when rendering big images.
I was studying how to improve the performance of the plug-in, but I don't know if I'm missing some detail.

I suggest rendering the full image and place it in the map, taking advantage of the GPU acceleration that CSS transformations are making use of.

If this approach is not feasible due to texture size limit (I tested loading images of several sizes like 32k x 32k in Firefox 93 and I did not find any problem) or something like that, the projection function could be remade using WebAssembly or gpu-js in a worker.

What do you think?
Thanks in advance for your time.

**Comment by Mforcen** [comment]
I have been testing the proposed image pipeline and big images render way faster now. It creates only a node image and apply CSS transformations to it.
I would like to add Cloud Optimized GeoTIFF support by creating a grid of image nodes, but I would like someone to review the code in order to know if it is worth the effort.

The url repo is this one: https://github.com/Mforcen/leaflet-geotiff-2/tree/leaflet-geotiff-2-direct-render

**Comment by mttucl** [comment]
Hi,
I'm interested in this but the repo link is not working. Also, if using a local file, is there a need to redraw when zooming/panning?

**Comment by Mforcen** [comment]
Hi, I removed the repo since I was no longer working on this topic.

If you need some guidance on this, the issue here is that the plugin recalculates the image when it is moved around the screen by calling the _drawImage function in the object or something like this.

I do not fully remember what I did, but by removing the canvas and only letting the image in place and transforming it using CSS it should work.

**Comment by mttucl** [comment]
I understand and appreciate the pointers. Unfortunately, I don't know how to achieve this as I'm still learning.

What I did is save the `rasterImageData` and in `_drawImage` I only call render if there is no `rasterImageData`. It is not ideal but works much faster. Also, I'm using rgb render. if using plotly, it might be an issue if would like to update image data colors etc..

Also, I commented `map.on("moveend", this._reset, this)`. I'm not sure why it needs to be called as the image doesn't rescale when panning. The only issue I see now is the image jump off before reszing when zoomin fast/close but not a big deal. I hope this can help others.

**Comment by mttucl** [comment]
It seems `map.on("moveend", this._reset, this)` is needed when zooming inside the image as not all the image is rendered. When the whole image is visible, it is not needed. Also, not sure if `rasterImageData` is saved in memory as my file is 100 MB but performance is much better for now. I believe your solution is better for anyone knows how to.

**Comment by mttucl** [comment]
Sorry to bug you on this, but if you happen to have a copy of your file, I'm very interested to see your solution.
