### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by pinky2070500** [danwild/leaflet-geotiff-2#39]
I'm getting the following error when trying to put a GeoTIFF image on the map page. Although I followed the instructions. Please help me
![image](https://user-images.githubusercontent.com/97578341/170471125-fbe70d6b-0f6f-42de-90be-7df9bd39acd9.png)

below is my code
    idw () {
      const url = "http://gsnc.local/projects/gsnc/storage/raster/home/idw_muivi_wgs84_1653559785.tif";
      var layer = L.leafletGeotiff(url).addTo(this.map);
    },
    
I use vue + leaflet to build WebGIS

**Comment by pinky2070500** [comment]
![image](https://user-images.githubusercontent.com/97578341/170476578-6f19320b-7dce-4c45-a30d-6a3d7493045b.png)

**Comment by danwild** [comment]
First step - confirm if this _is_ actually an issue with this plugin and not another problem. 

i.e. what's up with the first `net::ERR_BLOCKED_BY_CLIENT` error..? [Adblocker?](https://stackoverflow.com/questions/22318119/i-am-getting-failed-to-load-resource-neterr-blocked-by-client-with-google-chr)

**Comment by pinky2070500** [comment]
> 

of course I uninstalled Adb. :(

**Comment by pinky2070500** [comment]
I have definitely disabled all extensions, but still get this error. I tried both demo data but still got this error.

**Comment by danwild** [comment]
You will need to provide more info @pinky2070500 

Can you provide a minimal codepen so the error can be reproduced?
What exactly have you tried to debug the error?
What other browsers have you tried to confirm it's not a chrome/browser issue?
Have you tried to perform a vanilla [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) on that .tif file to confirm a successful XHR request outside of this plugin is possible in your development env?

**Comment by pinky2070500** [comment]
https://codesandbox.io/s/df5hz?file=/src/Map.js:1140-1145
when i open this it gives error, net::ERR_BLOCKED_BY_CLIENT
![image](https://user-images.githubusercontent.com/97578341/171778410-ccd5ab34-d297-4c09-9af0-157138b52081.png)

I use windows 11 and chorme version 102.0.5005.63

**Comment by danwild** [comment]
I cannot reproduce the issue you describe using your example, it works as expected:

![image](https://user-images.githubusercontent.com/3774647/171794542-6dfbb0f4-a23a-4fdb-9daf-acbe9eaea97e.png)

I suggest you try some of my previous suggestions.

**Comment by pinky2070500** [comment]
Thank you so much, i have removed and reinstalled chorme. Everything is ok!

**Comment by pinky2070500** [comment]
This error is caused by the extension of IDM Integration Module
fix: should update to latest IDM or disable it

**Comment by pinky2070500** [comment]
hi sir, I tried to upload my gtiff image but it doesn't work, I'm getting this error, please help

Failed to load from url or blob http://gsnc.local/projects/gsnc/storage/raster/home/idw_muivi_wgs84_1654590709.tif TypeError: Invalid byte order value.
at eval (geotiff.js?bea3:347:1)
at h (geotiff.js?bea3:2:1)
at Generator.eval [as _invoke] (geotiff.js?bea3:2:1)
at t. [as next] (geotiff.js?bea3:2:1)
at n (geotiff.js?bea3:20:1)
at c (geotiff.js?bea3:20:1)
eval @ leaflet-geotiff.js?c8fa:159
leaflet-geotiff.js?c8fa:184 this.setBand threw error TypeError: this.tiff.getImage is not a function
at i.setBand (leaflet-geotiff.js?c8fa:239:1)
at i._processTIFF (leaflet-geotiff.js?c8fa:183:1)
at i._getData (leaflet-geotiff.js?c8fa:176:1)
eval @ leaflet-geotiff.js?c8fa:184
leaflet-geotiff.js?c8fa:188 Uncaught (in promise) TypeError: this.tiff.getImage is not a function
at i._processTIFF (leaflet-geotiff.js?c8fa:188:1)

![image](https://user-images.githubusercontent.com/97578341/172336452-54dbfaf0-be9c-4c17-8e29-1241efe53b2a.png)
