### ISSUE TITLE
Have you guys ever had any complaints about this software stack not working with Safari or on IOS devices?

### ISSUE THREAD

**Issue by lstillwe** [danwild/leaflet-geotiff-2#4]
Have you guys ever had any complaints about this software stack not working with Safari or on IOS devices? Raster values do not seem to get read properly or at least the values are zeroed out in this software stack. Plotty, Geotiff JS, and Leaflet-Geotiff-2 - when run in Safari, or any browser on an iOS device. There are no errors reported by the browser.

**Comment by danwild** [comment]
Hi @lstillwe, yes - I have had issues, which have typically been inherited from the underlying [geotiffjs](https://github.com/geotiffjs/geotiff.js) lib (which does most of the heavy lifting) e.g. https://github.com/geotiffjs/geotiff.js/issues/160

I've just published `v0.2.5` which uses the latest version of gretiffjs so should hopefully address some of these problems.
