### ISSUE TITLE
Support for pane for vectorArrows

### ISSUE THREAD

**Issue by stardustcafe** [danwild/leaflet-geotiff-2#40]
I tried to provide pane option using
` L.LeafletGeotiff.vectorArrows(
{
arrowSize: 15,
pane:"wdir"
});`

This doesn't work. Can this be supported?

**Comment by danwild** [comment]
Hi @stardustcafe, `pane` should be set via `L.leafletGeotiff` options, not the renderer's options.

**Comment by stardustcafe** [comment]
I initially did give the option to leafletGeotiff and it didn't work. So I tried it with vectorArrows. Let me try once again.

**Comment by stardustcafe** [comment]
Okay.. It works. Thank you for the response @danwild .
